### ISSUE TITLE
Error when running 'yo jquery-boilerplate'

### ISSUE THREAD

**Issue by visualcookie** [jquery-boilerplate/generator-jquery-boilerplate#13]
Hi,

I get an error when running the generator. Below are some information about it.

Command run: **yo jquery-boilerplate**

Log:
```/usr/local/lib/node_modules/generator-jquery-boilerplate/app/index.js:7
  var files   = this.expandFiles('**/*', { cwd: this.sourceRoot(), dot: true }
                                                     ^
TypeError: undefined is not a function
    at new module.exports (/usr/local/lib/node_modules/generator-jquery-boilerplate/app/index.js:7:54)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:318:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:86:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:61:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:48:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:150:1)
    at Module._compile (module.js:460:26)```

**Comment by kuldipem** [comment]
I am also getting this error.

**Comment by surajair** [comment]
me too

**Comment by edpittol** [comment]
+1

**Comment by visualcookie** [comment]
I really hope that this repository  isn't dead at all.

**Comment by seansean11** [comment]
+1 I'm not sure if this is the culprit, but according to npm the package is at version 1.2.0 which was released August 8. 2013 [link text](https://www.npmjs.com/package/generator-jquery-boilerplate).  And, according to the repo the just released version 0.2.0 last month.  Looks like we are not installing the newest version.

**Comment by pipozoft** [comment]
+1

**Comment by heldr** [comment]
Fixed and updated on npm registry :tea:
